### ISSUE TITLE
UBS及插座，不定时自己关闭掉！

### ISSUE THREAD

**Issue by suifeng009** [qlwz/esp_dc1#1]
很感谢大神开发的固件，目前测试，USB及插座会不定时自己关闭，一共刷了6个。已经发现有2个出现这样的问题了！

**Comment by qlwz** [comment]
开启web开启，上日志， 另外看看时间是不是重新上电了。

**Comment by suifeng009** [comment]
日志  00:00:00 ---------------------  v2020.02.16.1400  2020-02-16 14:56:59  -------------------（就这一排没有其他的）
开始时间：2020-02-17 01:55:31 (时间感觉不对，应该是12点前就通电了)
自己断电表现在第一次刚通电那前几分钟。我现在开了一个晚上目前正常！继续测试看会不会出现问题！感谢大神的回复！

**Comment by qlwz** [comment]
上电 连接WIFI- 5分钟连不上wifi 进入 ap模式 2分钟后 重启。

**Comment by suifeng009** [comment]
明白了。昨天接入WIFI后，稳定一天了！大佬这个功能能单独一个选线是否开启不？怕如果WIFI掉了。就全部掉线要重写配置。开关名称，能做到像论坛模块直接在MQTT发现改中文名字不？不需要自己上配置文件？谢谢大佬！

**Comment by qlwz** [comment]
测试了多天，还有问题不？

**Comment by suifeng009** [comment]
这几天没有出现，应该是您说的没配网进入ap模式，我后开发现一个问题，就是我不管怎么设置，比如我开 开关1 开关2会跟着开，只能还原出厂，不知道是不是bug。

**Comment by qlwz** [comment]
总开关会记忆 分开关的状态，当分开关开的时候，关闭总开关 分开开关也会随着关闭，开的时候也会打开。 选择分开关不联动可以解决。

**Comment by suifeng009** [comment]
里面的选项我都测试过，就是不行，重置秒好，搞不清楚。目前一切正常。
