### ISSUE TITLE
DC1掉电重上电记忆掉电前状态有时候不一致

### ISSUE THREAD

**Issue by nblky** [qlwz/esp_dc1#15]
测试方法如下：
1.插座孔控制开关1,2,3，开2，关2，开1,3；掉电再上电，记忆理应1,3上电，实际为2上电

######

通过日志发现，记忆功能是触发后10秒才会保存

**Comment by nblky** [comment]
查看日志发现 记忆开关状态时间从12秒到30秒时间不等

**Comment by qlwz** [comment]
设计如此，定时存储的。
