### ISSUE TITLE
导出的ha配置文件中不含state主题

### ISSUE THREAD

**Issue by byff** [qlwz/esp_dc1#2]
![image](https://user-images.githubusercontent.com/4739508/74643930-7c510580-51b0-11ea-8ff5-b41bf2ced1a4.png)
state_topic内容不正确导致HA中无法反馈开关的状态
修改为dc1/dc1_shufang/stat/POWER2可以正常反馈

最后感谢大佬提供的固件。

**Comment by qlwz** [comment]
似乎没有连接成功MQTT成功导致的。

**Comment by byff** [comment]
> 似乎没有连接成功MQTT成功导致的。

再次尝试没问题，有可能是mqtt没连接成功就下载了
再次感谢

**Comment by qlwz** [comment]
已经修复了。

**Comment by byff** [comment]
> 已经修复了。

大神辛苦了
